In [1]:
import numpy as np

In [1]:
print('Hello World!')

Hello World!


In [8]:
b = [1, 2, 3]

In [9]:
b.reverse()

In [10]:
b

[3, 2, 1]

In [11]:
b?

In [15]:
def add_numbers(a, b):
    """
    Add two numbers together

    Returns
    -------
    the_sum : type of arguments
    """
    return a + b

In [16]:
add_numbers?

In [17]:
add_numbers??

In [22]:
np.*load*?

In [23]:
%run ipython_script_test.py

In [24]:
c

7.5

In [25]:
result

1.4666666666666666

In [1]:
def append_element(some_list, element):
    some_list.append(element)

In [2]:
data = [1, 2, 3]

In [3]:
append_element(data, 4)

In [4]:
data

[1, 2, 3, 4]

In [5]:
tup = (4, 5, 6)

In [6]:
a, b, c = tup

In [7]:
b

5

In [2]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 17.3 ms, sys: 7.21 ms, total: 24.6 ms
Wall time: 24.2 ms


In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 651 ms, sys: 176 ms, total: 828 ms
Wall time: 827 ms


In [6]:
data = np.random.randn(2,3)

In [7]:
data

array([[-0.95474153,  1.21541132, -1.38090901],
       [-0.87251492,  0.18049244, -0.98731447]])

In [8]:
data * 10

array([[ -9.54741527,  12.15411321, -13.80909014],
       [ -8.72514919,   1.80492441,  -9.8731447 ]])

In [9]:
data + data

array([[-1.90948305,  2.43082264, -2.76181803],
       [-1.74502984,  0.36098488, -1.97462894]])

In [10]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

In [12]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [13]:
arr1.dtype

dtype('float64')

In [14]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
arr2.shape

(2, 4)

In [16]:
arr2.ndim

2

In [18]:
arr2.dtype

dtype('int64')

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
np.empty((2, 3, 2))

array([[[-0.00000000e+000, -0.00000000e+000],
        [ 7.90505033e-323,  0.00000000e+000],
        [ 2.12199579e-314,  4.82337433e+228]],

       [[ 6.14415221e-144,  1.16097020e-028],
        [ 7.25385566e-043,  2.73703598e-052],
        [ 6.75942037e-067,  3.97062373e+246]]])

In [23]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [25]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [26]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [27]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [28]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [30]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [31]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [32]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [2]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [3]:
data

array([[-0.528559  , -0.87121835, -2.24631245,  0.67837236],
       [ 0.87473956, -0.76942365,  0.0768836 ,  0.85566321],
       [-0.32700181,  0.88942585,  2.74099639,  1.54785204],
       [ 0.7272296 ,  0.50653282, -0.69235045, -0.9474111 ],
       [ 0.17724823, -0.75767597,  0.34238921, -0.04136404],
       [ 0.51042474, -0.4005624 , -0.85127072, -0.27114422],
       [-0.37384948,  2.21794218,  0.5621469 ,  0.16829086]])

In [4]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [5]:
data[names == 'Bob']

array([[-0.528559  , -0.87121835, -2.24631245,  0.67837236],
       [ 0.7272296 ,  0.50653282, -0.69235045, -0.9474111 ]])

In [6]:
data[names == 'Bob', 2:]

array([[-2.24631245,  0.67837236],
       [-0.69235045, -0.9474111 ]])

In [7]:
data[names == 'Bob', 3]

array([ 0.67837236, -0.9474111 ])

In [8]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [9]:
data[~(names == 'Bob')]

array([[ 0.87473956, -0.76942365,  0.0768836 ,  0.85566321],
       [-0.32700181,  0.88942585,  2.74099639,  1.54785204],
       [ 0.17724823, -0.75767597,  0.34238921, -0.04136404],
       [ 0.51042474, -0.4005624 , -0.85127072, -0.27114422],
       [-0.37384948,  2.21794218,  0.5621469 ,  0.16829086]])

In [10]:
mask = (names == 'Bob') | (names == 'Will')

In [11]:
mask

array([ True, False,  True,  True,  True, False, False])

In [12]:
data[mask]

array([[-0.528559  , -0.87121835, -2.24631245,  0.67837236],
       [-0.32700181,  0.88942585,  2.74099639,  1.54785204],
       [ 0.7272296 ,  0.50653282, -0.69235045, -0.9474111 ],
       [ 0.17724823, -0.75767597,  0.34238921, -0.04136404]])

In [14]:
data[data < 0] = 0
data

array([[0.        , 0.        , 0.        , 0.67837236],
       [0.87473956, 0.        , 0.0768836 , 0.85566321],
       [0.        , 0.88942585, 2.74099639, 1.54785204],
       [0.7272296 , 0.50653282, 0.        , 0.        ],
       [0.17724823, 0.        , 0.34238921, 0.        ],
       [0.51042474, 0.        , 0.        , 0.        ],
       [0.        , 2.21794218, 0.5621469 , 0.16829086]])

In [15]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.87473956, 0.        , 0.0768836 , 0.85566321],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.51042474, 0.        , 0.        , 0.        ],
       [0.        , 2.21794218, 0.5621469 , 0.16829086]])

In [16]:
# Fancy Indexing

In [17]:
arr = np.empty((8, 4))

In [18]:
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [19]:
# subset of rows in defined order

In [20]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [21]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [22]:
# pass multiple index arrays - selects 1D array of index tuples

In [24]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [25]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [26]:
# rectangular region from selecting a subset of matrix rows and columns

In [28]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])